### ISSUE TITLE
CMake error: string sub-command REPLACE requires at least four arguments

### ISSUE THREAD

**Issue by Mel-Chen** [sifive/BSC-RVV#1]
```
mkdir debug
cd debug
cmake .. -DUSE_AUTO_VEC=1
```
It will failed at line 23 in CMakeLists.txt. 
```
string(REPLACE "-Wl,--disable-new-dtags" "" CMAKE_EXE_LINKER_FLAGS ${CMAKE_EXE_LINKER_FLAGS})
```
If `CMAKE_EXE_LINKER_FLAGS` is empty, cmake probably interpret the function arguments as less 4.

So far I can work around by `cmake .. -DUSE_AUTO_VEC=1 -DCMAKE_EXE_LINKER_FLAGS="-Wl,--disable-new-dtags"`.

**Comment by knute-sifive** [comment]
I can reproduce...

**Comment by knute-sifive** [comment]
I added that line some time ago before I realized I was using an older machine.  I've removed it and it appears the auto vectorization is working (at least for blackscholes).

**Comment by knute-sifive** [comment]
For my memory -- this is on branch `sparta`.

**Comment by knute-sifive** [comment]
Fixed in commit https://github.com/sifive/BSC-RVV/commit/18ab94481a2cf5b56334e6c1867bf3a097b5f4fe
